// ===================================================
// EXERCICES D'ÉVEIL (HISTOIRE / GÉOGRAPHIE / SCIENCES)
// ===================================================

window.GEO_BELGIQUE_QCM = [
  {q:"Quel est le chef-lieu de la province de Hainaut ?", options:["Namur","Charleroi","Mons"], correct:2},
  {q:"Quel est le chef-lieu de la province du Luxembourg ?", options:["Arlon","Bastogne","Liège"], correct:0},
  {q:"Quel est le chef-lieu de la province de Flandre orientale ?", options:["Bruges","Gand","Anvers"], correct:1},
  {q:"Quel est le chef-lieu de la province du Brabant flamand ?", options:["Bruxelles","Hasselt","Louvain"], correct:2},
  {q:"Quel est le chef-lieu de la province du Limbourg ?", options:["Hasselt","Genk","Louvain"], correct:0},
  {q:"Quelle province a Namur comme chef-lieu ?", options:["La province de Liège","La province de Namur","La province du Hainaut"], correct:1},
  {q:"Quelle province a Bruges comme chef-lieu ?", options:["La province de Flandre occidentale","La province du Brabant flamand","La province de Flandre orientale"], correct:0},
  {q:"Quelle province a Wavre comme chef-lieu ?", options:["La province de Namur","La province du Brabant wallon","La province de Liège"], correct:1},
  {q:"Combien de provinces y a-t-il en Belgique ?", options:["10","5","8"], correct:0},
  {q:"Quelle ville ne fait partie d'aucune province ?", options:["Verviers","Anvers","Bruxelles"], correct:2},
{q:"Dans quelle région se trouve la province de Liège ?", options:["En région wallonne","En région Bruxelles-Capitale","En région flamande"], correct:0},
  {q:"Combien de régions compte la Belgique ?", options:["Deux","Quatre","Trois"], correct:2},
  {q:"Quelle est la région la plus peuplée de Belgique ?", options:["La région wallonne","La région flamande","La région Bruxelles-Capitale"], correct:1},
  {q:"Combien de communautés compte la Belgique ?", options:["Trois","Deux","Quatre"], correct:0},
  {q:"À quelle communauté appartient la province de Liège ?", options:["À la communauté flamande","À la Fédération Wallonie-Bruxelles","À la communauté germanophone"], correct:1},
  {q:"Quelle est la plus petite communauté de Belgique ?", options:["La Fédération Wallonie-Bruxelles","La communauté germanophone","La communauté flamande"], correct:1},
  {q:"Combien de communes y a-t-il en Belgique en 2026 ?", options:["322 communes","907 communes","565 communes"], correct:2},
  {q:"La capitale de notre pays se trouve...", options:["En région wallonne","En région flamande","En région Bruxelles-Capitale"], correct:2},
  {q:"La communauté germanophone se trouve en...", options:["Région flamande","Région germanophone","Région wallonne"], correct:2},
  {q:"Combien de langues officielles compte la Belgique ?", options:["Deux","Trois","Quatre"], correct:1},
  {q:"Quelle langue parle-t-on principalement en région flamande ?", options:["Le français","L'allemand","Le néerlandais"], correct:2},
  {q:"Dans quelle province belge parle-t-on officiellement allemand ?", options:["Dans la province du Luxembourg","Dans la province de Liège","Dans la province de Namur"], correct:1},
  {q:"Quelle langue parle-t-on à Bruxelles ?", options:["Le français, le néerlandais et l'allemand","Le français et le néerlandais","Uniquement le français"], correct:1},
  {q:"Les langues officielles de Belgique sont...", options:["Le français, le néerlandais et l'anglais","Le français, le néerlandais, l'allemand et l'anglais","Le français, le néerlandais et l'allemand"], correct:2},
  {q:"Par combien de pays la Belgique est-elle entourée ?", options:["Cinq","Quatre","Trois"], correct:1},
  {q:"Quel pays se trouve au nord de la Belgique ?", options:["Le Luxembourg","Les Pays-Bas","La France"], correct:1},
  {q:"Quel pays se trouve à l'est de la Belgique ?", options:["Les Pays-Bas","La France","L'Allemagne"], correct:2},
  {q:"Quels pays se trouvent au sud de la Belgique ?", options:["L'Allemagne et les Pays-Bas","Le Luxembourg et la France","La France et l'Espagne"], correct:1},
  {q:"Quel océan ou mer borde la Belgique à l'ouest ?", options:["La mer Méditerranée","La mer du Nord","L'océan Atlantique"], correct:1},
  {q:"La province du Luxembourg partage sa frontière avec...", options:["L'Allemagne","Les Pays-Bas","La France"], correct:2},
  {q:"Quel est le plus long fleuve de Belgique ?", options:["La Sambre","La Meuse","L'Escaut"], correct:1},
  {q:"Dans quelle mer se jette l'Escaut ?", options:["Dans la mer du Nord","Dans l'océan Atlantique","Dans la mer Méditerranée"], correct:0},
  {q:"Quel cours d'eau traverse la ville de Liège ?", options:["L'Ourthe","La Sambre","La Meuse"], correct:2},
  {q:"Quel cours d'eau coule près de Waimes ?", options:["La Semois","La Warche","La Meuse"], correct:1},
  {q:"Quel cours d'eau est un affluent de la Meuse ?", options:["L'Escaut","La Warchenne","La Sambre"], correct:2},
  {q:"Comment s'appelle le point culminant de Belgique ?", options:["Le mont des Ardennes","Le Signal de Botrange","Le pic des Fagnes"], correct:1},
  {q:"À quelle altitude se trouve le Signal de Botrange ?", options:["À 794 mètres","À 694 mètres","À 594 mètres"], correct:1},
  {q:"Dans quelle province se trouve le Signal de Botrange ?", options:["Dans la province de Namur","Dans la province de Liège","Dans la province du Luxembourg"], correct:1},
  {q:"Comment s'appelle le plateau situé autour du Signal de Botrange ?", options:["Le plateau des Ardennes","Le plateau de Herve","Le plateau des Hautes Fagnes"], correct:2},
  {q:"Quelle région naturelle se trouve au sud de la Belgique ?", options:["La Campine","Les Ardennes","Le Condroz"], correct:1},
  {q:"Quelle province belge borde la mer du Nord ?", options:["La province d'Anvers","La province de Flandre occidentale","La province de Flandre orientale"], correct:1},
  {q:"La commune de Waimes se situe...", options:["En moyenne Belgique","En haute Belgique","En basse Belgique"], correct:1},
  {q:"Quelle commune est voisine de Waimes au nord ?", options:["Stavelot","Eupen","Malmedy"], correct:1},
  {q:"Quelle commune est voisine de Waimes à l'est ?", options:["Bullange","Amblève","Bütgenbach"], correct:2},
  {q:"Dans quelle province se trouve Waimes ?", options:["Dans la province du Luxembourg","Dans la province de Liège","Dans la province de Namur"], correct:1},
  {q:"Dans quelle région se trouve Waimes ?", options:["En région flamande","En région wallonne","En région Bruxelles-Capitale"], correct:1},
  {q:"Laquelle de ces communes n'est pas une voisine de Waimes ?", options:["Bütgenbach","Malmedy","Stavelot"], correct:2},
  {q:"Quelle est la capitale de la Belgique ?", options:["Anvers","Bruxelles","Liège"], correct:1},
  {q:"Quelle est la plus grande ville de Belgique en nombre d'habitants ?", options:["Liège","Anvers","Bruxelles"], correct:1},
  {q:"Où prend-on les décisions importantes concernant l'école ?", options:["À la province de Liège","À la région wallonne","À la Fédération Wallonie-Bruxelles"], correct:2},
];

window.GEO_PLANISPHERES = [
  {
    id: 'europe',
    titre: "Planisphère classique — centré sur l'Europe",
    img: 'planisphere_europe.jpg',
    zones: [
      {id:'OArc',    label:'Océan Arctique',    x:47.3, y:1.3,  w:8, h:6},
      {id:'AmNord',  label:'Amérique du Nord',  x:8.4,  y:19.8, w:8, h:6},
      {id:'Europe',  label:'Europe',            x:43.8, y:20.9, w:8, h:6},
      {id:'Asie',    label:'Asie',              x:67.3, y:20.0, w:8, h:6},
      {id:'OAtl',    label:'Océan Atlantique',  x:25.6, y:39.4, w:8, h:6},
      {id:'Afrique', label:'Afrique',           x:44.0, y:41.0, w:8, h:6},
      {id:'OPacG',   label:'Océan Pacifique',   x:0.3,  y:48.5, w:7, h:6},
      {id:'AmSud',   label:'Amérique du Sud',   x:19.1, y:60.0, w:8, h:6},
      {id:'OInd',    label:'Océan Indien',      x:64.3, y:54.8, w:8, h:6},
      {id:'Oceanie', label:'Océanie',           x:84.9, y:65.5, w:8, h:6},
      {id:'OPacD',   label:'Océan Pacifique',   x:89.4, y:36.5, w:7, h:6},
      {id:'OAus',    label:'Océan Austral',     x:44.9, y:86.4, w:8, h:6},
      {id:'Antarct', label:'Antarctique',       x:53.2, y:93.6, w:8, h:6},
    ]
  },
  {
    id: 'amerique',
    titre: "Planisphère centré sur l'Amérique",
    img: 'planisphere_amerique.png',
    zones: [
      {id:'OArc',    label:'Océan Arctique',    x:28.2, y:2.6,  w:8, h:6},
      {id:'AsieG',   label:'Asie',              x:11.2, y:17.7, w:8, h:6},
      {id:'AmNord',  label:'Amérique du Nord',  x:44.0, y:26.2, w:8, h:6},
      {id:'OPac',    label:'Océan Pacifique',   x:28.8, y:45.5, w:8, h:6},
      {id:'OAtl',    label:'Océan Atlantique',  x:59.2, y:39.5, w:8, h:6},
      {id:'AmSud',   label:'Amérique du Sud',   x:55.6, y:61.4, w:8, h:6},
      {id:'Europe',  label:'Europe',            x:72.6, y:26.2, w:8, h:6},
      {id:'Afrique', label:'Afrique',           x:74.3, y:45.4, w:8, h:6},
      {id:'AsieD',   label:'Asie',              x:85.6, y:25.5, w:8, h:6},
      {id:'OIndG',   label:'Océan Indien',      x:3.0,  y:59.9, w:7, h:6},
      {id:'OIndD',   label:'Océan Indien',      x:86.1, y:58.2, w:7, h:6},
      {id:'Oceanie', label:'Océanie',           x:16.6, y:70.0, w:8, h:6},
      {id:'OAus',    label:'Océan Austral',     x:46.1, y:92.7, w:8, h:6},
    ]
  },
  {
    id: 'indien',
    titre: "Planisphère centré sur l'Océan Indien",
    img: 'planisphere_indien.png',
    zones: [
      {id:'OArc',    label:'Océan Arctique',    x:4.7,  y:9.5,  w:8, h:6},
      {id:'Europe',  label:'Europe',            x:9.6,  y:30.4, w:8, h:6},
      {id:'Asie',    label:'Asie',              x:36.1, y:25.4, w:8, h:6},
      {id:'Afrique', label:'Afrique',           x:11.2, y:50.8, w:8, h:6},
      {id:'OInd',    label:'Océan Indien',      x:26.0, y:65.3, w:8, h:6},
      {id:'Oceanie', label:'Océanie',           x:41.4, y:73.1, w:8, h:6},
      {id:'AmNord',  label:'Amérique du Nord',  x:72.9, y:29.4, w:8, h:6},
      {id:'AmSud',   label:'Amérique du Sud',   x:84.1, y:67.1, w:8, h:6},
      {id:'OPac',    label:'Océan Pacifique',   x:57.0, y:50.0, w:8, h:6},
      {id:'OAtlG',   label:'Océan Atlantique',  x:1.0,  y:65.3, w:7, h:6},
      {id:'OAtlD',   label:'Océan Atlantique',  x:90.0, y:42.2, w:7, h:6},
      {id:'OAus',    label:'Océan Austral',     x:46.7, y:93.2, w:8, h:6},
    ]
  },
  {
    id: 'arctique',
    titre: 'Vue du Pôle Nord',
    img: 'planisphere_arctique.png',
    zones: [
      {id:'OArc',    label:'Océan Arctique',    x:46.7, y:46.2, w:8, h:6},
      {id:'OAtl',    label:'Océan Atlantique',  x:57.0, y:87.7, w:8, h:6},
      {id:'OPac',    label:'Océan Pacifique',   x:15.6, y:19.7, w:8, h:6},
      {id:'AmNord',  label:'Amérique du Nord',  x:13.1, y:65.9, w:8, h:6},
      {id:'Europe',  label:'Europe',            x:79.1, y:67.0, w:8, h:6},
      {id:'Asie',    label:'Asie',              x:66.4, y:17.3, w:8, h:6},
    ]
  },
  {
    id: 'antarctique',
    titre: 'Vue du Pôle Sud',
    img: 'planisphere_antarctique.png',
    zones: [
      {id:'Antarct', label:'Antarctique',       x:48.4, y:49.6, w:8, h:6},
      {id:'OAusH',   label:'Océan Austral',     x:53.6, y:31.1, w:8, h:6},
      {id:'OAusB',   label:'Océan Austral',     x:36.9, y:64.9, w:8, h:6},
      {id:'AmSud',   label:'Amérique du Sud',   x:6.7,  y:27.6, w:8, h:6},
      {id:'Oceanie', label:'Océanie',           x:71.5, y:81.5, w:8, h:6},
      {id:'Afrique', label:'Afrique',           x:64.9, y:7.5,  w:8, h:6},
      {id:'OAtl',    label:'Océan Atlantique',  x:34.4, y:5.6,  w:8, h:6},
      {id:'OInd',    label:'Océan Indien',      x:89.8, y:43.1, w:8, h:6},
      {id:'OPac',    label:'Océan Pacifique',   x:14.7, y:77.6, w:8, h:6},
    ]
  },
];

window.SCI_TRAJET_SANG_TEXTES = [
  {
    id: 'A',
    titre: 'Le cœur comme pompe',
    segments: [
      {type:'text', content:'Le '},
      {type:'blank', answer:'cœur', id:'A1'},
      {type:'text', content:" est un "},
      {type:'blank', answer:'muscle', id:'A2'},
      {type:'text', content:" situé dans la "},
      {type:'blank', answer:'cage thoracique', id:'A3'},
      {type:'text', content:". Il fonctionne comme une "},
      {type:'blank', answer:'pompe', id:'A4'},
      {type:'text', content:" qui envoie le sang dans tout le corps. Quand il se contracte, il pousse le sang vers l'extérieur. Il est divisé en quatre cavités : deux oreillettes ("},
      {type:'blank', answer:'oreillette droite', id:'A5', group:'A_oreillettes'},
      {type:'text', content:" et "},
      {type:'blank', answer:'oreillette gauche', id:'A6', group:'A_oreillettes'},
      {type:'text', content:") et deux ventricules ("},
      {type:'blank', answer:'ventricule droit', id:'A7', group:'A_ventricules'},
      {type:'text', content:" et "},
      {type:'blank', answer:'ventricule gauche', id:'A8', group:'A_ventricules'},
      {type:'text', content:"). Le sang arrive dans les oreillettes et repart par les ventricules. Les "},
      {type:'blank', answer:'artères', id:'A9'},
      {type:'text', content:" transportent le sang du cœur vers les organes et les poumons. Les "},
      {type:'blank', answer:'veines', id:'A10'},
      {type:'text', content:" ramènent le sang des organes vers le cœur. Le cœur bat sans arrêt pour que le sang circule dans tout le corps."},
    ],
    mots: ['cœur','muscle','cage thoracique','pompe','oreillette droite','oreillette gauche','ventricule droit','ventricule gauche','artères','veines'],
  },
  {
    id: 'B',
    titre: 'La petite circulation',
    segments: [
      {type:'text', content:'La '},
      {type:'blank', answer:'petite circulation', id:'B1'},
      {type:'text', content:" est le trajet du sang entre le cœur et les "},
      {type:'blank', answer:'poumons', id:'B2'},
      {type:'text', content:". Elle commence dans le "},
      {type:'blank', answer:'ventricule droit', id:'B3'},
      {type:'text', content:" qui envoie le sang vers les poumons grâce à l'"},
      {type:'blank', answer:'artère pulmonaire', id:'B4'},
      {type:'text', content:". Les artères transportent toujours le sang du "},
      {type:'blank', answer:'cœur', id:'B5'},
      {type:'text', content:" vers les poumons ou les organes. Ce sang est chargé en "},
      {type:'blank', answer:'gaz carbonique', id:'B6'},
      {type:'text', content:", un déchet produit par les organes. Dans les poumons, le sang traverse de minuscules vaisseaux appelés "},
      {type:'blank', answer:'capillaires', id:'B7'},
      {type:'text', content:". Ces capillaires font le lien entre les artères et les veines : c'est là que se font les échanges gazeux. Le gaz carbonique est rejeté et l'"},
      {type:'blank', answer:'oxygène', id:'B8'},
      {type:'text', content:" est capté. Le sang, maintenant chargé en oxygène, repart vers le cœur par les "},
      {type:'blank', answer:'veines pulmonaires', id:'B9'},
      {type:'text', content:" et arrive dans l'"},
      {type:'blank', answer:'oreillette gauche', id:'B10'},
      {type:'text', content:". Les veines ramènent toujours le sang vers le cœur."},
    ],
    mots: ['petite circulation','poumons','ventricule droit','artère pulmonaire','cœur','gaz carbonique','capillaires','oxygène','veines pulmonaires','oreillette gauche'],
  },
  {
    id: 'C',
    titre: 'La grande circulation',
    segments: [
      {type:'text', content:'La '},
      {type:'blank', answer:'grande circulation', id:'C1'},
      {type:'text', content:" est le trajet du sang entre le cœur et les "},
      {type:'blank', answer:'organes', id:'C2'},
      {type:'text', content:" du corps. Elle commence dans le "},
      {type:'blank', answer:'ventricule gauche', id:'C3'},
      {type:'text', content:" qui se contracte pour envoyer le sang chargé en "},
      {type:'blank', answer:'oxygène', id:'C4'},
      {type:'text', content:" dans l'"},
      {type:'blank', answer:'artère aorte', id:'C5'},
      {type:'text', content:", la plus grande artère du corps. Les artères transportent le sang du cœur vers les organes. Dans les organes, le sang passe par de minuscules vaisseaux : les "},
      {type:'blank', answer:'capillaires', id:'C6'},
      {type:'text', content:". Ces capillaires font le lien entre les artères et les veines : c'est à leur niveau que l'oxygène est livré aux cellules et que le "},
      {type:'blank', answer:'gaz carbonique', id:'C7'},
      {type:'text', content:" est récupéré. Le sang revient ensuite au cœur par la "},
      {type:'blank', answer:'veine cave', id:'C8'},
      {type:'text', content:" et arrive dans l'"},
      {type:'blank', answer:'oreillette droite', id:'C9'},
      {type:'text', content:". Les "},
      {type:'blank', answer:'veines', id:'C10'},
      {type:'text', content:" ramènent toujours le sang des organes vers le cœur. La grande circulation assure ainsi l'alimentation en oxygène de tout l'organisme."},
    ],
    mots: ['grande circulation','organes','ventricule gauche','oxygène','artère aorte','capillaires','gaz carbonique','veine cave','oreillette droite','veines'],
  },
  {
    id: 'D',
    titre: 'Vue d\'ensemble',
    segments: [
      {type:'text', content:'Le '},
      {type:'blank', answer:'cœur', id:'D1'},
      {type:'text', content:" est un muscle creux situé dans la "},
      {type:'blank', answer:'cage thoracique', id:'D2'},
      {type:'text', content:". En se contractant, il joue le rôle d'une pompe et envoie le sang dans deux circuits. La "},
      {type:'blank', answer:'petite circulation', id:'D3'},
      {type:'text', content:" relie le cœur aux "},
      {type:'blank', answer:'poumons', id:'D4'},
      {type:'text', content:" : le sang y dépose son "},
      {type:'blank', answer:'gaz carbonique', id:'D5'},
      {type:'text', content:" et récupère de l'"},
      {type:'blank', answer:'oxygène', id:'D6'},
      {type:'text', content:". La "},
      {type:'blank', answer:'grande circulation', id:'D7'},
      {type:'text', content:" relie le cœur aux organes : elle distribue l'oxygène à toutes les cellules du corps. Dans les deux circuits, les "},
      {type:'blank', answer:'artères', id:'D8'},
      {type:'text', content:" transportent le sang du cœur vers les poumons ou les organes. Les "},
      {type:'blank', answer:'veines', id:'D9'},
      {type:'text', content:" ramènent le sang des organes et des poumons vers le cœur. Les "},
      {type:'blank', answer:'capillaires', id:'D10'},
      {type:'text', content:" font le lien entre les artères et les veines, là où se produisent les échanges gazeux."},
    ],
    mots: ['cœur','cage thoracique','petite circulation','poumons','gaz carbonique','oxygène','grande circulation','artères','veines','capillaires'],
  },
];

window.SCI_CIRCULATOIRE_QCM = [
  {q:"Le cœur est situé dans…", options:["la cage thoracique","la cage abdominale","la colonne vertébrale"], correct:"la cage thoracique"},
  {q:"Le cœur est un…", options:["organe creux et musculeux","organe plein et osseux","organe creux et cartilagineux"], correct:"organe creux et musculeux"},
  {q:"Le cœur est divisé en…", options:["4 cavités","3 cavités","2 cavités"], correct:"4 cavités"},
  {q:"Quand le cœur se contracte, il…", options:["pousse le sang vers l'extérieur","aspire le sang vers l'intérieur","filtre le sang"], correct:"pousse le sang vers l'extérieur"},
  {q:"Les artères transportent le sang…", options:["du cœur vers les organes et les poumons","des organes vers le cœur","des poumons vers les organes"], correct:"du cœur vers les organes et les poumons"},
  {q:"Les veines transportent le sang…", options:["des organes et des poumons vers le cœur","du cœur vers les organes","du cœur vers les poumons"], correct:"des organes et des poumons vers le cœur"},
  {q:"Les capillaires font le lien entre…", options:["les artères et les veines","le cœur et les poumons","les oreillettes et les ventricules"], correct:"les artères et les veines"},
  {q:"La petite circulation relie…", options:["le cœur et les poumons","le cœur et les organes","les poumons et les organes"], correct:"le cœur et les poumons"},
  {q:"La grande circulation relie…", options:["le cœur et les organes","le cœur et les poumons","les poumons et les organes"], correct:"le cœur et les organes"},
  {q:"L'artère pulmonaire transporte…", options:["le sang chargé en gaz carbonique","le sang chargé en oxygène","le sang chargé en nutriments"], correct:"le sang chargé en gaz carbonique"},
  {q:"Les veines pulmonaires transportent…", options:["le sang chargé en oxygène","le sang chargé en gaz carbonique","le sang chargé en nutriments"], correct:"le sang chargé en oxygène"},
  {q:"L'artère aorte transporte…", options:["le sang chargé en oxygène vers les organes","le sang chargé en gaz carbonique vers les poumons","le sang chargé en oxygène vers les poumons"], correct:"le sang chargé en oxygène vers les organes"},
  {q:"La veine cave ramène le sang…", options:["des organes vers l'oreillette droite","des poumons vers l'oreillette gauche","des organes vers le ventricule droit"], correct:"des organes vers l'oreillette droite"},
  {q:"C'est dans les capillaires que…", options:["les échanges gazeux ont lieu","le sang est fabriqué","le sang est filtré"], correct:"les échanges gazeux ont lieu"},
  {q:"Le ventricule gauche envoie le sang vers…", options:["l'artère aorte","l'artère pulmonaire","la veine cave"], correct:"l'artère aorte"},
  {q:"Le ventricule droit envoie le sang vers…", options:["l'artère pulmonaire","l'artère aorte","la veine cave"], correct:"l'artère pulmonaire"},
  {q:"L'oreillette gauche reçoit le sang venant…", options:["des veines pulmonaires","de la veine cave","de l'artère pulmonaire"], correct:"des veines pulmonaires"},
  {q:"L'oreillette droite reçoit le sang venant…", options:["de la veine cave","des veines pulmonaires","de l'artère aorte"], correct:"de la veine cave"},
  {q:"Dans les poumons, le sang se débarrasse de…", options:["son gaz carbonique","son oxygène","ses nutriments"], correct:"son gaz carbonique"},
  {q:"Dans les organes, les cellules reçoivent…", options:["de l'oxygène","du gaz carbonique","du sang artériel"], correct:"de l'oxygène"},
  {q:"Combien de cavités le cœur possède-t-il ?", options:["4 cavités : 2 oreillettes et 2 ventricules","4 cavités : 2 artères et 2 veines","3 cavités : 1 oreillette et 2 ventricules"], correct:"4 cavités : 2 oreillettes et 2 ventricules"},
  {q:"Le sang chargé en gaz carbonique est de couleur…", options:["rouge sombre","rouge vif","bleu"], correct:"rouge sombre"},
  {q:"Le sang chargé en oxygène est de couleur…", options:["rouge vif","rouge sombre","rose"], correct:"rouge vif"},
  {q:"Quel organe permet au sang de récupérer de l'oxygène ?", options:["les poumons","le foie","les reins"], correct:"les poumons"},
  {q:"Comment appelle-t-on le trajet du sang entre le cœur et les poumons ?", options:["la petite circulation","la grande circulation","la circulation pulmonaire"], correct:"la petite circulation"},
  {q:"Comment appelle-t-on le trajet du sang entre le cœur et les organes ?", options:["la grande circulation","la petite circulation","la circulation générale"], correct:"la grande circulation"},
  {q:"Quel est le plus grand vaisseau du corps humain ?", options:["l'artère aorte","la veine cave","l'artère pulmonaire"], correct:"l'artère aorte"},
  {q:"Les valvules du cœur servent à…", options:["empêcher le sang de revenir en arrière","pomper le sang vers les artères","filtrer le sang avant qu'il reparte"], correct:"empêcher le sang de revenir en arrière"},
  {q:"Que se passe-t-il dans les capillaires des organes ?", options:["L'oxygène est livré aux cellules et le gaz carbonique est récupéré","Le gaz carbonique est rejeté et l'oxygène est capté","Le sang est nettoyé et filtré"], correct:"L'oxygène est livré aux cellules et le gaz carbonique est récupéré"},
  {q:"Dans quelle cavité du cœur le sang arrive-t-il en premier lorsqu'il revient des organes ?", options:["l'oreillette droite","l'oreillette gauche","le ventricule droit"], correct:"l'oreillette droite"},
];

window.SCI_DIG_QCM_DATA = [
  {q:"Par où commence la digestion ?",opts:["La bouche","L'estomac","L'intestin grêle","Le foie"],correct:0},
  {q:"Quel organe produit la bile ?",opts:["Le foie","Le pancréas","L'estomac","Les reins"],correct:0},
  {q:"Où sont absorbés les nutriments ?",opts:["Dans l'intestin grêle","Dans l'estomac","Dans le gros intestin","Dans le foie"],correct:0},
  {q:"Comment s'appelle la masse d'aliments mâchés et mélangés à la salive ?",opts:["Le bol alimentaire","Le chyme","Les sucs gastriques","La bile"],correct:0},
  {q:"Quel liquide est produit par les glandes salivaires ?",opts:["La salive","La bile","Le suc gastrique","L'insuline"],correct:0},
  {q:"Combien mesure environ l'intestin grêle ?",opts:["6 à 7 mètres","1 mètre","15 mètres","50 cm"],correct:0},
  {q:"Quel autre nom donne-t-on au gros intestin ?",opts:["Le côlon","Le rectum","Le duodénum","L'appendice"],correct:0},
  {q:"Quel est le rôle de l'œsophage ?",opts:["Transporter les aliments de la gorge vers l'estomac","Digérer les graisses","Absorber les nutriments","Produire des enzymes"],correct:0},
  {q:"Quel organe produit les sucs gastriques ?",opts:["L'estomac","Le foie","Le pancréas","L'intestin grêle"],correct:0},
  {q:"Comment s'appelle le tube qui relie la bouche à l'estomac ?",opts:["L'œsophage","La trachée","Le duodénum","L'intestin grêle"],correct:0},
  {q:"Quel est le rôle de la salive ?",opts:["Ramollir les aliments et commencer la digestion","Absorber les nutriments","Produire des hormones","Filtrer le sang"],correct:0},
  {q:"Quelle est la fonction principale du foie dans la digestion ?",opts:["Produire la bile pour digérer les graisses","Absorber l'eau","Produire l'insuline","Stocker les déchets"],correct:0},
  {q:"Quel organe filtre le sang après l'absorption des nutriments ?",opts:["Le foie","Les reins","Le cœur","La rate"],correct:0},
  {q:"Quelle est la longueur approximative du gros intestin ?",opts:["1,5 mètre","7 mètres","30 cm","5 mètres"],correct:0},
  {q:"Quel est le rôle du rectum ?",opts:["Stocker les selles avant leur évacuation","Absorber les nutriments","Produire des enzymes","Filtrer les déchets"],correct:0},
  {q:"Pourquoi faut-il bien mâcher ses aliments ?",opts:["Pour faciliter la digestion et mélanger la salive","Pour produire plus de bile","Pour accélérer le transit","Pour absorber les vitamines"],correct:0},
  {q:"Quel organe est à la fois une glande digestive et endocrine ?",opts:["Le pancréas","Le foie","L'estomac","L'intestin grêle"],correct:0},
  {q:"Qu'est-ce que le bol alimentaire ?",opts:["La masse d'aliments mâchés et mélangés à la salive","Les sucs gastriques","Les selles","La bile"],correct:0},
  {q:"Qu'est-ce que la mastication ?",opts:["L'action de broyer les aliments avec les dents","L'action d'avaler","La production de salive","Le mouvement de l'estomac"],correct:0},
  {q:"Qu'est-ce que la déglutition ?",opts:["L'action d'avaler les aliments","L'action de mâcher","La digestion chimique","Le mouvement intestinal"],correct:0},
  {q:"Qu'est-ce que le brassage dans l'estomac ?",opts:["Le mouvement qui mélange les aliments aux sucs gastriques","La production de bile","L'absorption des nutriments","Le transit intestinal"],correct:0},
  {q:"Qu'est-ce que le suc gastrique ?",opts:["Un liquide acide produit par l'estomac pour digérer les aliments","Un liquide produit par le foie","Une hormone du pancréas","De la salive modifiée"],correct:0},
  {q:"Quel organe produit le suc pancréatique ?",opts:["Le pancréas","Le foie","L'estomac","L'intestin grêle"],correct:0},
  {q:"Qu'est-ce que le suc intestinal ?",opts:["Un liquide produit par l'intestin grêle qui achève la digestion","Un liquide de l'estomac","De la bile diluée","Un suc du gros intestin"],correct:0},
  {q:"Qu'est-ce que les contractions musculaires dans le tube digestif ?",opts:["Des mouvements qui poussent les aliments vers l'avant","Des mouvements qui produisent des sucs","Des contractions du cœur","Des mouvements respiratoires"],correct:0},
  {q:"Quel lien y a-t-il entre l'appareil digestif et l'appareil circulatoire ?",opts:["Les nutriments absorbés dans l'intestin grêle passent dans le sang","Le cœur pompe les sucs gastriques","Le foie produit le sang","Les intestins filtrent le sang"],correct:0},
  {q:"Comment les nutriments atteignent-ils les cellules du corps ?",opts:["Grâce au sang qui les transporte depuis l'intestin grêle","Par les nerfs","Par la lymphe uniquement","Par l'œsophage"],correct:0},
  {q:"Quel nutriment est principalement digéré dans la bouche ?",opts:["Les glucides (sucres)","Les protéines","Les graisses","Les vitamines"],correct:0},
  {q:"Qu'est-ce que la constipation ?",opts:["Difficulté à évacuer les selles","Excès de salive","Manque d'enzymes","Inflammation de l'estomac"],correct:0},
  {q:"Combien de dents a un adulte ?",opts:["32","20","28","36"],correct:0},
];

window.SCI_RESP_QCM_DATA = [
  {q:"Par où l'air entre-t-il dans le corps ?",opts:["Nez et bouche","Oreilles","Yeux","Peau"],correct:0},
  {q:"Comment s'appelle le tube qui relie la gorge aux poumons ?",opts:["Trachée artère","Oesophage","Bronche","Aorte"],correct:0},
  {q:"Combien de poumons possède l'être humain ?",opts:["2","1","3","4"],correct:0},
  {q:"Quel gaz l'organisme absorbe-t-il lors de la respiration ?",opts:["Oxygène","Dioxyde de carbone","Azote","Hydrogène"],correct:0},
  {q:"Quel gaz est rejeté lors de l'expiration ?",opts:["Dioxyde de carbone","Oxygène","Azote","Vapeur d'eau"],correct:0},
  {q:"Comment s'appellent les petits sacs dans les poumons où ont lieu les échanges gazeux ?",opts:["Alvéoles pulmonaires","Bronchioles","Capillaires","Vésicules"],correct:0},
  {q:"Quel muscle aide les poumons à se gonfler et à se dégonfler ?",opts:["Diaphragme","Coeur","Foie","Rate"],correct:0},
  {q:"Que font les bronches ?",opts:["Elles conduisent l'air dans chaque poumon","Elles filtrent le sang","Elles produisent de l'oxygène","Elles digèrent les aliments"],correct:0},
  {q:"Comment s'appelle l'action d'entrée de l'air dans les poumons ?",opts:["L'inspiration","L'expiration","La circulation","La digestion"],correct:0},
  {q:"Comment s'appelle l'action de sortie de l'air des poumons ?",opts:["L'expiration","L'inspiration","La transpiration","La respiration"],correct:0},
  {q:"Les bronches se divisent en… ?",opts:["Bronchioles","Alvéoles","Capillaires","Veines"],correct:0},
  {q:"Où se font les échanges entre l'air et le sang ?",opts:["Dans les alvéoles pulmonaires","Dans la trachée","Dans les bronches","Dans le nez"],correct:0},
  {q:"Quel organe pompe le sang oxygéné vers le corps ?",opts:["Le coeur","Le poumon","Le foie","Les reins"],correct:0},
  {q:"Combien de fois par minute un enfant respire-t-il en moyenne ?",opts:["20 fois","5 fois","60 fois","100 fois"],correct:0},
  {q:"Quelle est la fonction principale de l'appareil respiratoire ?",opts:["Apporter de l'oxygène au sang","Digérer les aliments","Filtrer le sang","Produire de l'énergie"],correct:0},
  {q:"La trachée artère se divise en combien de bronches ?",opts:["2","3","4","1"],correct:0},
  {q:"Qu'est-ce que le diaphragme ?",opts:["Un muscle situé sous les poumons","Un os de la cage thoracique","Une veine","Un poumon"],correct:0},
  {q:"Que se passe-t-il quand le diaphragme s'abaisse ?",opts:["Les poumons se gonflent (inspiration)","Les poumons se dégonflent","Le sang circule plus vite","Le coeur s'arrête"],correct:0},
  {q:"De quoi sont essentiellement composés nos poumons ?",opts:["D'air et de sang","D'air et d'os","D'air et d'eau","D'air et de graisse"],correct:0},
  {q:"Comment appelle-t-on le réseau de vaisseaux sanguins autour des alvéoles ?",opts:["Les capillaires","Les veines","Les artères","Les bronchioles"],correct:0},
  {q:"Où se trouvent les poumons ?",opts:["Dans la cage thoracique","Dans l'abdomen","Dans la tête","Dans le bassin"],correct:0},
  {q:"Quel est le rôle des cils dans le nez ?",opts:["Filtrer les poussières","Produire de l'oxygène","Réchauffer le sang","Conduire l'air"],correct:0},
  {q:"Pourquoi un des deux poumons est-il plus petit que l'autre ?",opts:["Car le coeur est situé plus près d'un des 2 poumons","Car ils n'ont pas le même rôle","Car c'est une malformation chez tout le monde","Car il y a un poumon pour l'inspiration et un pour l'expiration"],correct:0},
  {q:"Pourquoi ne faut-il pas fumer ?",opts:["La fumée détruit les alvéoles et la trachée","La fumée agrandit le nombre d'alvéoles dans les poumons","La fumée bloque l'arrivée de l'air par le nez","La fumée détruit les capillaires dans les alvéoles"],correct:0},
  {q:"Les poumons sont entourés d'une membrane appelée… ?",opts:["La plèvre","Le péricarde","La muqueuse","Le diaphragme"],correct:0},
  {q:"Qu'est-ce que l'asthme ?",opts:["Une maladie qui rétrécit les bronches","Une infection des alvéoles","Un problème de coeur","Une maladie du nez"],correct:0},
  {q:"Quel sport améliore la capacité pulmonaire ?",opts:["La natation","Les échecs","La lecture","Le dessin"],correct:0},
  {q:"Combien de lobes possède le poumon droit ?",opts:["3","2","4","1"],correct:0},
  {q:"Quel gaz représente environ 21% de l'air que nous respirons ?",opts:["L'oxygène","Le dioxyde de carbone","L'azote","L'hélium"],correct:0},
  {q:"Qu'est-ce que la capacité pulmonaire ?",opts:["Le volume d'air que les poumons peuvent contenir","La vitesse de respiration","La pression du sang","La taille des bronches"],correct:0},
];

window.EMOJI_SVG_MAP = {
    '🔠': `<img src="assets/logos/jeu_mots_croises.png" class="w-full h-full object-contain" alt="Mots croisés" />`,
    '🔎': `<img src="assets/logos/jeu_mots_caches.png" class="w-full h-full object-contain" alt="Mots cachés" />`,
    '🔢': `<img src="assets/logos/jeu_sudoku.png" class="w-full h-full object-contain" alt="Sudoku" />`,
    // Emojis de Français, Conjugaison & Lecture
    '📚': `<img src="assets/logos/lecture_narrative.png" class="w-full h-full object-contain" alt="Lecture" />`,
    '📖': `<img src="assets/logos/lecture_informative.png" class="w-full h-full object-contain" alt="Lecture" />`,
    '📰': `<img src="assets/logos/lecture_informative.png" class="w-full h-full object-contain" alt="Article" />`,
    '🖼️': `<img src="assets/logos/lecture_descriptive.png" class="w-full h-full object-contain" alt="Description" />`,
    '🔍': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.637 10.637Z" /></svg>`,
    '💬': `<img src="assets/logos/lecture_argumentative.png" class="w-full h-full object-contain" alt="Débat" />`,
    '🏷️': `<img src="assets/logos/classes_mots.png" class="w-full h-full object-contain" alt="Classes" />`,
    '🔖': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z" /></svg>`,
    '🎨': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M9.53 16.122a3 3 0 0 0-5.78 1.128 2.25 2.25 0 0 1-2.4 2.245 4.5 4.5 0 0 0 8.4-1.245c0-.778-.367-1.478-.93-1.928Zm0 0a5.003 5.003 0 0 1 6.008-6.008m-.008.008a3 3 0 0 0 2.244-2.244 2.25 2.25 0 0 1 2.245-2.4 4.5 4.5 0 0 0-1.245 8.4c-.778 0-1.478-.367-1.928-.93Zm0 0c-.45.563-.45 1.478 0 1.928m0 0a3 3 0 0 0 2.244 2.244 2.25 2.25 0 0 1 2.245 2.4 4.5 4.5 0 0 0-1.245 8.4c-.778 0-1.478.367-1.928.93Z" /></svg>`,
    '⚡': `<img src="assets/logos/lecture_rapide.png" class="w-full h-full object-contain" alt="Rapide" />`,
    '👤': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" /></svg>`,
    '🔄': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" /></svg>`,
    '🔗': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 0 1 1.242 7.244l-4.5 4.5a4.5 4.5 0 0 1-6.364-6.364l1.757-1.757m13.35-.622 1.757-1.757a4.5 4.5 0 0 0-6.364-6.364l-4.5 4.5a4.5 4.5 0 0 0 1.242 7.244" /></svg>`,
    '👑': `<img src="assets/logos/fonctions_mots.png" class="w-full h-full object-contain" alt="Fonctions" />`,
    '📌': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z" /></svg>`,
    '🔀': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M7.5 21 3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5" /></svg>`,
    '📍': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" /><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25s-7.5-4.108-7.5-11.25a7.5 7.5 0 1 1 15 0Z" /></svg>`,
    '🌟': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499c.15-.326.621-.326.772 0l2.062 4.183 4.582.668c.36.053.504.498.243.755l-3.315 3.23.78 4.567c.061.359-.318.634-.64 1.24l-4.1-2.155-4.1 2.155c-.322.176-.701-.1-.64-.46l.78-4.567-3.315-3.23c-.26-.257-.116-.702.243-.755l4.582-.668 2.062-4.183Z" /></svg>`,
    '❓': `<img src="assets/logos/types_phrases.png" class="w-full h-full object-contain" alt="Types de phrases" />`,
    '🗺️': `<img src="assets/logos/geographie.png" class="w-full h-full object-contain" alt="Géographie" />`,
    '💧': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21a6.75 6.75 0 0 0 6.75-6.75c0-3.329-2.362-7.142-5.748-10.454a1.5 1.5 0 0 0-2.004 0C7.612 7.108 5.25 10.921 5.25 14.25A6.75 6.75 0 0 0 12 21Z" /></svg>`,
    '🏘️': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" /></svg>`,
    '✖️': `<img src="assets/logos/op_multiplier.png" class="w-full h-full object-contain" alt="Multiplier" />`,
    '➕': `<img src="assets/logos/op_plus.png" class="w-full h-full object-contain" alt="Plus" />`,
    '➖': `<img src="assets/logos/op_moins.png" class="w-full h-full object-contain" alt="Moins" />`,
    '➗': `<img src="assets/logos/op_diviser.png" class="w-full h-full object-contain" alt="Diviser" />`,
    '🃏': `<img src="assets/logos/jeu_memory.png" class="w-full h-full object-contain" alt="Memory" />`,
    '🟦': `<img src="assets/logos/jeu_tetris.png" class="w-full h-full object-contain" alt="Tetris" />`,
    '🚗': `<img src="assets/logos/jeu_rushhour.png" class="w-full h-full object-contain" alt="Rush Hour" />`,
    '🤖': `<img src="assets/logos/jeu_robot.png" class="w-full h-full object-contain" alt="Robot" />`,
    '🎮': `<img src="assets/logos/subject_jeux.png" class="w-full h-full object-contain" alt="Jeux" />`,
    '🏰': `<img src="assets/logos/histoire.png" class="w-full h-full object-contain" alt="Histoire" />`,
    '🎵': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M9 19V6l12-3v13M9 10l12-3" /><circle cx="6" cy="19" r="3" fill="currentColor" fill-opacity="0.1" /><circle cx="18" cy="16" r="3" fill="currentColor" fill-opacity="0.1" /></svg>`,
    '🚀': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.126A59.768 59.768 0 0 1 21.485 12 59.77 59.77 0 0 1 3.27 20.876L6 12Zm0 0h7.5" /></svg>`,
    '✅': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" /></svg>`,
    '✈️': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.27 3.126A59.768 59.768 0 0 1 21.485 12 59.77 59.77 0 0 1 3.27 20.876L6 12Zm0 0h7.5" /></svg>`,
    '👁️': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" /><circle cx="12" cy="12" r="3" /></svg>`,
    '↕️': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M3 7.5 7.5 3m0 0L12 7.5M7.5 3v13.5m13.5 0L16.5 21m0 0L12 16.5m4.5 4.5V7.5" /></svg>`,
    '⚖️': `<img src="assets/logos/grandeurs.png" class="w-full h-full object-contain" alt="Grandeurs" />`,
    '🔢': `<img src="assets/logos/numeration.png" class="w-full h-full object-contain" alt="Numération" />`,
    '🔣': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" /></svg>`,
    '½': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="6" y1="18" x2="18" y2="6" /><text x="4" y="11" font-size="10" font-family="sans-serif" font-weight="bold" fill="currentColor">1</text><text x="12" y="19" font-size="10" font-family="sans-serif" font-weight="bold" fill="currentColor">2</text></svg>`,
    '%': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="6" y1="18" x2="18" y2="6" /><circle cx="8" cy="8" r="2.5" /><circle cx="16" cy="16" r="2.5" /></svg>`,
    '🎲': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="3" /><circle cx="8" cy="8" r="1.5" fill="currentColor" /><circle cx="16" cy="16" r="1.5" fill="currentColor" /><circle cx="12" cy="12" r="1.5" fill="currentColor" /></svg>`,
    '📊': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z" /></svg>`,
    '🔟': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="3" /><text x="6" y="16" font-size="14" font-family="sans-serif" font-weight="black" fill="currentColor">10</text></svg>`,
    '5️⃣': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="3" /><text x="8.5" y="16" font-size="14" font-family="sans-serif" font-weight="black" fill="currentColor">5</text></svg>`,
    '9️⃣': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="3" /><text x="8.5" y="16" font-size="14" font-family="sans-serif" font-weight="black" fill="currentColor">9</text></svg>`,
    '🧩': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M14.25 9.75 16.5 12l-2.25 2.25m-4.5 0L7.5 12l2.25-2.25M6 20.25h12A2.25 2.25 0 0 0 20.25 18V6A2.25 2.25 0 0 0 18 3.75H6A2.25 2.25 0 0 0 3.75 6v12A2.25 2.25 0 0 0 6 20.25Z" /></svg>`,
    '📏': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M3 8.25h18M5 8.25v2M8 8.25v2M11 8.25v3M14 8.25v2M17 8.25v2M20 8.25v2M3 15.75h18" /></svg>`,
    '📐': `<img src="assets/logos/solides_figures.png" class="w-full h-full object-contain" alt="Géométrie" />`,
    '📦': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="m21 7.5-9-5.25L3 7.5m18 0-9 5.25m9-5.25v9l-9 5.25M3 7.5l9 5.25M3 7.5v9l9 5.25" /></svg>`,
    '⏱️': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="13" r="8" /><path d="M12 5V2M10 2h4M12 9v4l3 3" stroke-linecap="round" /></svg>`,
    '💶': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2" /><circle cx="12" cy="12" r="3" fill="currentColor" fill-opacity="0.1" /><path d="M6 8h.01M18 16h.01" stroke-linecap="round" stroke-width="3" /></svg>`,
    '⬡': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3l8.66 5v10L12 21l-8.66-5V8z" /></svg>`,
    '🔺': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3l9 16H3z" /></svg>`,
    '🔲': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="2" /></svg>`,
    '💎': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 3h12l4 6-10 12L2 9z" /></svg>`,
    '🦴': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M6 8c-2-2-4.5.5-2.5 2.5l10.5 10.5c2 2.5 4.5 0 2.5-2l-10.5-10.5Z" /></svg>`,
    '🏺': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M8 3h8M12 3v3m-5 3a5 5 0 0 0 10 0V6H7v3Zm0 0c0 4.5 2 9 5 9s5-4.5 5-9M9 21h6m-3-3v3" /></svg>`,
    '⚓': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 5V2m-3 9h6M12 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6Zm0 6v7m0 0a6 6 0 0 1-5.2-3m5.2 3a6 6 0 0 0 5.2-3M4 14l1 1m15-1-1 1" /></svg>`,
    '🏭': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M3 21h18M3 21V10l5 4V10l5 4V6l8 6v9" /></svg>`,
    '📅': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2" /><line x1="16" y1="2" x2="16" y2="6" /><line x1="8" y1="2" x2="8" y2="6" /><line x1="3" y1="10" x2="21" y2="10" /></svg>`,
    '🏆': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm0 0v4.5m0-4.5H8.25m3.75 0H15.75m-6 4.5H13.5m-6-9H4.5m0 0c0-2.25 1.75-4.5 4.5-4.5M19.5 6h-3.75m3.75 0c0-2.25-1.75-4.5-4.5-4.5" /></svg>`,
    '🫁': `<img src="assets/logos/sciences_respiratoire.png" class="w-full h-full object-contain" alt="Poumons" />`,
    '🫃': `<img src="assets/logos/sciences_digestif.png" class="w-full h-full object-contain" alt="Estomac" />`,
    '❤️': `<img src="assets/logos/sciences_circulatoire.png" class="w-full h-full object-contain" alt="Cœur" />`,
    '🩸': `<img src="assets/logos/sciences_circulatoire.png" class="w-full h-full object-contain" alt="Sang" />`,
    '💨': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M3 12h12M6 8h10M4 16h8" /></svg>`,
    '🧴': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="7" y="8" width="10" height="12" rx="2" /><path d="M12 4v4M10 4h4" stroke-linecap="round" /></svg>`,
    '💀': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3a7 7 0 0 0-7 7v3a2 2 0 0 0 2 2h1v3h8v-3h1a2 2 0 0 0 2-2v-3a7 7 0 0 0-7-7Z" /><circle cx="9.5" cy="10" r="1.5" fill="currentColor" /><circle cx="14.5" cy="10" r="1.5" fill="currentColor" /></svg>`,
    '⚙️': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3" /><path stroke-linecap="round" stroke-linejoin="round" d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" /></svg>`,
    '🪐': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="5" /><path stroke-linecap="round" stroke-linejoin="round" d="M3.75 15.75c3-1.5 6-3 9-4.5s5.5-2.25 7.5-3.75" /></svg>`,
    '⏰': `<img src="assets/logos/conjugaison.png" class="w-full h-full object-contain" alt="Conjugaison" />`,
    '📝': `<img src="assets/logos/expression_ecrite.png" class="w-full h-full object-contain" alt="Écriture" />`,
    '🔤': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="3" width="8" height="8" rx="1" /><rect x="13" y="13" width="8" height="8" rx="1" /><text x="5" y="10" font-size="8" font-family="sans-serif" font-weight="black" fill="currentColor">A</text><text x="15" y="20" font-size="8" font-family="sans-serif" font-weight="black" fill="currentColor">B</text></svg>`,
    '🎯': `<img src="assets/logos/jeu_tables.png" class="w-full h-full object-contain" alt="Calcul rapide" />`,
    '✍️': `<img src="assets/logos/expression_ecrite.png" class="w-full h-full object-contain" alt="Écriture" />`,
    '✏️': `<img src="assets/logos/expression_ecrite.png" class="w-full h-full object-contain" alt="Crayon" />`,
    '🏫': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21V11m0 0h5a2 2 0 012 2v8M12 11H7a2 2 0 00-2 2v8M12 2L4 8v3h16V8L12 2Z" /></svg>`,
    '🧠': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 18.5a6.5 6.5 0 1 1 0-13 6.5 6.5 0 0 1 0 13Zm0-13c-2.5 0-4.5 1.5-4.5 4s2 3 4.5 3m0-7c2.5 0 4.5 1.5 4.5 4s-2 3-4.5 3" /></svg>`,
    '🏛️': `<img src="assets/logos/histoire.png" class="w-full h-full object-contain" alt="Histoire" />`,
    '🔬': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm-3-8v16m-6-3h12" /></svg>`,
    '🌍': `<img src="assets/logos/geographie.png" class="w-full h-full object-contain" alt="Géographie" />`,
    '🟣': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity="0.1" /></svg>`,
    '🔵': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity="0.15" /></svg>`,
    '🔴': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity="0.2" /></svg>`,
    '🟡': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity="0.1" /></svg>`,
    '🟠': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity="0.15" /></svg>`,
    '🟢': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity="0.15" /></svg>`,
    '⭐': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499c.15-.326.621-.326.772 0l2.062 4.183 4.582.668c.36.053.504.498.243.755l-3.315 3.23.78 4.567c.061.359-.318.634-.64 1.24l-4.1-2.155-4.1 2.155c-.322.176-.701-.1-.64-.46l.78-4.567-3.315-3.23c-.26-.257-.116-.702.243-.755l4.582-.668 2.062-4.183Z" /></svg>`,
    '💯': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="3" /><text x="4" y="16" font-size="12" font-family="sans-serif" font-weight="black" fill="currentColor">100</text></svg>`,
    '🍴': `<svg class="w-8 h-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2M7 2v4M21 15V2a5 5 0 0 0-5 5v8c0 1.1.9 2 2 2h3ZM12 11v11M18 17v5" /></svg>`,
    '👩‍🏫': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="12" rx="1" fill="currentColor" fill-opacity="0.1" /><rect x="3" y="4" width="18" height="12" rx="1" /><path d="M7 16l-2 5M17 16l2 5M12 16v5" stroke-linecap="round" stroke-linejoin="round"/><path d="M7 8h4M7 11h7" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    '🗄️': `<svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="2" /><path d="M4 12h16M8 8h8M8 16h8" stroke-linecap="round" /></svg>`
};
