// ===================================================
// EXERCICES DE FRANÇAIS
// Structure : EXERCICES_FRANCAIS[matiere][temps]
// ===================================================

window.EXERCICES_FRANCAIS = {

  conjugaison: {

    futur: {
      // Banque de 50 questions QCM
      qcm_bank: [
        {text:"Demain, je ___ (aller) chez le médecin.", options:["irai","allerai","irais"], answer:0},
        {text:"L'année prochaine, tu ___ (avoir) douze ans.", options:["avoiras","auras","aurais"], answer:1},
        {text:"Ce soir, il ___ (être) en retard.", options:["sera","serat","serait"], answer:0},
        {text:"Nous ___ (faire) un gâteau pour l'anniversaire.", options:["fairons","ferrons","ferons"], answer:2},
        {text:"Vous ___ (venir) nous rendre visite dimanche.", options:["venirez","viendrez","viendriez"], answer:1},
        {text:"Ils ___ (pouvoir) partir dès demain.", options:["pourront","pouveront","pourraient"], answer:0},
        {text:"Elle ___ (vouloir) sûrement un cadeau.", options:["voudrait","vouloira","voudra"], answer:2},
        {text:"Je ___ (savoir) nager l'été prochain.", options:["savrai","saurai","savoirai"], answer:1},
        {text:"Tu ___ (voir) tes amis ce week-end.", options:["verras","voiras","voieras"], answer:0},
        {text:"Il ___ (venir) nous aider demain matin.", options:["venira","viendrait","viendra"], answer:2},
        {text:"Nous ___ (devoir) travailler plus dur.", options:["devrons","devoirons","devoirerons"], answer:0},
        {text:"Vous ___ (savoir) la vérité bientôt.", options:["savoirez","saurez","sauriez"], answer:1},
        {text:"Elles ___ (tenir) leur promesse.", options:["teniront","tiendriont","tiendront"], answer:2},
        {text:"Je ___ (recevoir) mon cadeau demain.", options:["recevrai","recevrais","recevoirai"], answer:0},
        {text:"Tu ___ (mourir) de rire en voyant ça !", options:["mouriras","mourras","mourriras"], answer:1},
        {text:"Il ___ (courir) le marathon l'an prochain.", options:["courra","courera","courirait"], answer:0},
        {text:"Nous ___ (envoyer) une lettre à nos grands-parents.", options:["envoierons","envoyerons","enverrons"], answer:2},
        {text:"Vous ___ (appeler) le médecin si nécessaire.", options:["appelerez","appellerez","appèlerez"], answer:1},
        {text:"Elles ___ (jeter) leurs vieux jouets.", options:["jetteront","jèteront","jeteront"], answer:0},
        {text:"Je ___ (acheter) du pain ce soir.", options:["achètterai","achetterai","achèterai"], answer:2},
        {text:"Tu ___ (se lever) tôt demain matin.", options:["te levereas","te lèveras","te levras"], answer:1},
        {text:"Il ___ (falloir) travailler davantage.", options:["faudra","faudrait","falloira"], answer:0},
        {text:"Nous ___ (valoir) mieux que ça !", options:["valerons","vaudriont","vaudrons"], answer:2},
        {text:"Vous ___ (cueillir) des fruits dans le jardin.", options:["cueillirez","cueillerez","cueillrez"], answer:1},
        {text:"Elles ___ (acquérir) de l'expérience.", options:["acquerront","acquériront","acquerriront"], answer:0},
        {text:"Je ___ (mettre) ma veste s'il pleut.", options:["mettrerai","metterai","mettrai"], answer:2},
        {text:"Il ___ (pleuvoir) demain selon la météo.", options:["pleuvroira","pleuvra","pleuvera"], answer:1},
        {text:"Grâce à la météo, les plantes ___ (grandir) vite.", options:["grandiront","grandisseront","grandirront"], answer:0},
        {text:"Vous me ___ (dire) la vérité.", options:["diterez","direrez","direz"], answer:2},
        {text:"Elles ___ (fuir) si elles ont peur.", options:["fuieront","fuiront","fuirront"], answer:1},
        {text:"Je ___ (haïr) attendre, mais je patienterai.", options:["haïrai","hairai","haierat"], answer:0},
        {text:"Tu ___ (bouillir) d'impatience en attendant les résultats.", options:["bouiliras","bouillirais","bouilliras"], answer:2},
        {text:"Il ___ (dormir) mieux après cette journée.", options:["dormerat","dormira","dormirait"], answer:1},
        {text:"Nous ne ___ (mentir) pas — nous dirons la vérité.", options:["mentirons","mentironts","mentirions"], answer:0},
        {text:"Vous ___ (partir) en vacances la semaine prochaine.", options:["partirerez","partirez","partiriez"], answer:1},
        {text:"Elles ___ (sentir) bon après ce bain de fleurs.", options:["sentironts","sentiront","sentiraient"], answer:1},
        {text:"Je ___ (sortir) dès que j'aurai fini.", options:["sortirai","sortirais","sortirrai"], answer:0},
        {text:"Tu ___ (servir) les invités avec plaisir.", options:["servireras","serviras","servirais"], answer:1},
        {text:"Il ___ (ouvrir) la fenêtre pour aérer.", options:["ouvrera","ouvrira","ouvrirait"], answer:1},
        {text:"Nous ___ (offrir) un cadeau à notre professeur.", options:["offrironts","offrirons","offririons"], answer:1},
        {text:"Vous ___ (souffrir) moins avec ce médicament.", options:["souffrirerez","souffrirez","souffririez"], answer:1},
        {text:"Elles ___ (coudre) les costumes pour le spectacle.", options:["couderont","coudreront","coudront"], answer:2},
        {text:"Je ___ (conduire) prudemment sur cette route.", options:["conduirais","conduirai","conduierat"], answer:1},
        {text:"Tu ___ (écrire) une lettre à ton correspondant.", options:["écrirait","écriras","écrieras"], answer:1},
        {text:"Il ___ (lire) ce livre en une journée.", options:["lirait","lira","lirerat"], answer:1},
        {text:"Nous ___ (rire) bien en regardant ce film.", options:["rirons","rirerons","rirrons"], answer:0},
        {text:"Vous ___ (suivre) le guide pendant la visite.", options:["suivrerez","suivrez","suivriez"], answer:1},
        {text:"Elles ___ (vivre) à l'étranger après leurs études.", options:["viveront","vivreront","vivront"], answer:2},
        {text:"Je ___ (résoudre) ce problème rapidement.", options:["résoudrais","résolverai","résoudrai"], answer:2},
        {text:"Tu ___ (naître) sous une bonne étoile !", options:["naîtrais","naîtras","naîtera"], answer:1},
      ],

      // Banque de 50 phrases à trous
      trous_bank: [
        {before:"La semaine prochaine, nous", after:"un contrôle de mathématiques.", verb:"avoir", answer:"aurons"},
        {before:"Demain matin, tu", after:"le premier arrivé en classe.", verb:"être", answer:"seras"},
        {before:"Dans deux ans, elle", after:"ses études primaires.", verb:"finir", answer:"finira"},
        {before:"Ce soir, ils", after:"leurs forces pour déplacer le meuble.", verb:"unir", answer:"uniront"},
        {before:"Bientôt, je", after:"jouer de la guitare.", verb:"savoir", answer:"saurai"},
        {before:"L'année prochaine, vous", after:"participer au voyage scolaire.", verb:"pouvoir", answer:"pourrez"},
        {before:"Demain, elle", after:"un nouveau cartable pour la rentrée.", verb:"acheter", answer:"achètera"},
        {before:"À la fin de l'année, tu", after:"tes vieux cahiers.", verb:"jeter", answer:"jetteras"},
        {before:"Ce soir, il", after:"ses grands-parents pour leur anniversaire.", verb:"appeler", answer:"appellera"},
        {before:"Au printemps, l'eau", after:"le long des chemins de montagne.", verb:"ruisseler", answer:"ruissèlera"},
        {before:"Demain, nous", after:"les enfants au parc d'attractions.", verb:"emmener", answer:"emmènerons"},
        {before:"Chaque matin, tu", after:"la main pour répondre aux questions.", verb:"lever", answer:"lèveras"},
        {before:"Ce film long", after:"les plus jeunes spectateurs.", verb:"ennuyer", answer:"ennuiera"},
        {before:"L'entreprise", after:"cinquante personnes supplémentaires l'an prochain.", verb:"employer", answer:"emploiera"},
        {before:"La semaine prochaine, je", after:"ma lettre au père Noël.", verb:"envoyer", answer:"enverrai"},
        {before:"Après le repas, vous", after:"la vaisselle ensemble.", verb:"essuyer", answer:"essuierez"},
        {before:"Dans quelques semaines, il", after:"complètement de sa blessure.", verb:"guérir", answer:"guérira"},
        {before:"Cet été, tu", after:"au moins trois romans.", verb:"lire", answer:"liras"},
        {before:"Demain, nous", after:"une lettre à notre correspondant belge.", verb:"écrire", answer:"écrirons"},
        {before:"Ce soir, elle", after:"sa plus belle robe pour la fête.", verb:"mettre", answer:"mettra"},
        {before:"Quand tu seras grand, tu", after:"la vérité en toutes circonstances.", verb:"dire", answer:"diras"},
        {before:"Ce week-end, nous", after:"une randonnée en forêt.", verb:"faire", answer:"ferons"},
        {before:"À la fête, les enfants", after:"du jus de fruits.", verb:"boire", answer:"boiront"},
        {before:"L'artiste", after:"un grand tableau pour l'exposition.", verb:"peindre", answer:"peindra"},
        {before:"Je ne", after:"jamais à mes parents.", verb:"mentir", answer:"mentirai"},
        {before:"Tu", after:"ta promesse, j'en suis sûr.", verb:"tenir", answer:"tiendras"},
        {before:"Le directeur", after:"les nouveaux élèves à la rentrée.", verb:"accueillir", answer:"accueillera"},
        {before:"Ce soir, vous", after:"sûrement regarder un film.", verb:"vouloir", answer:"voudrez"},
        {before:"L'été prochain, nous", after:"en vacances en Italie.", verb:"aller", answer:"irons"},
        {before:"Dans une semaine, tu", after:"ta commande par la poste.", verb:"recevoir", answer:"recevras"},
        {before:"Bientôt, elle", after:"de son voyage au Canada.", verb:"revenir", answer:"reviendra"},
        {before:"L'année prochaine, vous", after:"travailler encore plus dur.", verb:"devoir", answer:"devrez"},
        {before:"Demain, ils", after:"leur père pour la première fois depuis un mois.", verb:"voir", answer:"verront"},
        {before:"Il", after:"partir tôt pour éviter les embouteillages.", verb:"falloir", answer:"faudra"},
        {before:"Ensemble, nous", after:"ce problème difficile.", verb:"résoudre", answer:"résoudrons"},
        {before:"Après l'école, tu", after:"tes amis au parc.", verb:"rejoindre", answer:"rejoindras"},
        {before:"Ce soir, il", after:"son chien chez le vétérinaire.", verb:"amener", answer:"amènera"},
        {before:"En voyant cette araignée, elle", after:"de s'approcher.", verb:"craindre", answer:"craindra"},
        {before:"La semaine prochaine, je", after:"mon premier semi-marathon.", verb:"courir", answer:"courrai"},
        {before:"Tes cousins", after:"te rendre visite pendant les vacances.", verb:"venir", answer:"viendront"},
        {before:"Sans soins, cette plante", after:"rapidement.", verb:"mourir", answer:"mourra"},
        {before:"Grand-mère", after:"les costumes pour le spectacle de fin d'année.", verb:"coudre", answer:"coudra"},
        {before:"Dans dix ans, ils", after:"peut-être à l'étranger.", verb:"vivre", answer:"vivront"},
        {before:"Tu", after:"prudemment quand tu auras ton permis.", verb:"conduire", answer:"conduiras"},
        {before:"Nous", after:"bien en regardant cette comédie ce soir.", verb:"rire", answer:"rirons"},
        {before:"Vous", after:"le guide tout au long de la visite du musée.", verb:"suivre", answer:"suivrez"},
        {before:"Demain, il", after:"son nouveau magasin en centre-ville.", verb:"ouvrir", answer:"ouvrira"},
        {before:"Pour Noël, nous", after:"un livre à chacun de nos amis.", verb:"offrir", answer:"offrirons"},
        {before:"Dès que tu auras fini tes devoirs, tu", after:"jouer dehors.", verb:"sortir", answer:"sortiras"},
        {before:"Dans quelques minutes, le soleil", after:"sur la montagne.", verb:"se lever", answer:"se lèvera"},
      ],

      // Évaluation fixe (une seule tentative)
      evaluation: {
        qcm: [
          {text:"Demain, je ___ (aller) chez le médecin.", options:["irai","allerai","irais"], answer:0},
          {text:"L'année prochaine, tu ___ (avoir) douze ans.", options:["avoiras","auras","aurais"], answer:1},
          {text:"Ils ___ (pouvoir) partir dès demain.", options:["pourront","pouveront","pourraient"], answer:0},
          {text:"Elle ___ (vouloir) sûrement un cadeau.", options:["voudrait","vouloira","voudra"], answer:2},
          {text:"Nous ___ (envoyer) une lettre à nos grands-parents.", options:["envoierons","envoyerons","enverrons"], answer:2},
        ],
        trous: [
          {before:"Dans deux ans, elle", after:"ses études primaires.", verb:"finir", answer:"finira"},
          {before:"Demain, elle", after:"un nouveau cartable pour la rentrée.", verb:"acheter", answer:"achètera"},
          {before:"Ce soir, il", after:"ses grands-parents pour leur anniversaire.", verb:"appeler", answer:"appellera"},
          {before:"L'artiste", after:"un grand tableau pour l'exposition.", verb:"peindre", answer:"peindra"},
          {before:"Sans soins, cette plante", after:"rapidement.", verb:"mourir", answer:"mourra"},
        ]
      }
    }


    ,present: {
      qcm_bank: [
        {text:"En ce moment, je ___ (aller) à l'école à pied.", options:["vais","vas","alle"], answer:0},
        {text:"Tu ___ (avoir) l'air fatigué ce matin.", options:["aies","as","avait"], answer:1},
        {text:"Il ___ (être) très content de ses résultats.", options:["est","es","ait"], answer:0},
        {text:"Nous ___ (finir) notre travail avant midi.", options:["finisons","finirons","finissons"], answer:2},
        {text:"Vous ___ (unir) vos efforts pour réussir.", options:["unissiez","unissez","uniez"], answer:1},
        {text:"Ils ___ (savoir) déjà leurs tables de multiplication.", options:["savent","saves","savoirent"], answer:0},
        {text:"Elle ___ (pouvoir) venir demain si elle veut.", options:["peud","peuve","peut"], answer:2},
        {text:"Je ___ (acheter) mes légumes au marché chaque samedi.", options:["achètte","achète","achette"], answer:1},
        {text:"Tu ___ (jeter) toujours tes affaires par terre.", options:["jettes","jètes","jetes"], answer:0},
        {text:"Il ___ (appeler) ses amis tous les soirs.", options:["appèle","apelle","appelle"], answer:2},
        {text:"L'eau ___ (ruisseler) le long des rochers après la pluie.", options:["ruissèle","ruissèlle","ruisele"], answer:0},
        {text:"Elle ___ (emmener) ses enfants à l'école chaque matin.", options:["emmenne","emmène","emmènne"], answer:1},
        {text:"Je ___ (lever) la main pour répondre.", options:["lèves","leve","lève"], answer:2},
        {text:"Ce long discours ___ (ennuyer) tout le monde.", options:["ennuie","ennuye","ennuiet"], answer:0},
        {text:"L'entreprise ___ (employer) deux cents personnes.", options:["employe","emploie","emploiet"], answer:1},
        {text:"Je ___ (envoyer) un message à mes parents.", options:["envoye","envoiet","envoie"], answer:2},
        {text:"Tu ___ (essuyer) la table après le repas.", options:["essuies","essuyies","essuyes"], answer:0},
        {text:"Elle ___ (guérir) rapidement grâce aux médicaments.", options:["guèrit","guériit","guérit"], answer:2},
        {text:"Je ___ (lire) un livre passionnant en ce moment.", options:["lis","li","lie"], answer:0},
        {text:"Nous ___ (écrire) une lettre à notre correspondant.", options:["écrirons","écrivons","écrivont"], answer:1},
        {text:"Tu ___ (mettre) ton manteau avant de sortir.", options:["mes","mais","mets"], answer:2},
        {text:"Il ___ (dire) toujours la vérité.", options:["dit","dis","di"], answer:0},
        {text:"Nous ___ (faire) du sport chaque mercredi.", options:["fesons","faisons","fezons"], answer:1},
        {text:"Les enfants ___ (boire) du lait chaque matin.", options:["buvent","boirent","boivent"], answer:2},
        {text:"L'artiste ___ (peindre) un magnifique tableau.", options:["peint","peind","peindt"], answer:0},
        {text:"Tu ne ___ (mentir) jamais à tes parents.", options:["ments","mens","mentes"], answer:1},
        {text:"Elle ___ (tenir) la main de son petit frère.", options:["tienne","tiend","tient"], answer:2},
        {text:"Le directeur ___ (accueillir) les visiteurs avec le sourire.", options:["accueille","acueillit","accueilles"], answer:0},
        {text:"Je ___ (vouloir) un verre d'eau, s'il te plaît.", options:["veus","veux","voule"], answer:1},
        {text:"Nous ___ (aller) au cinéma ce soir.", options:["alions","alons","allons"], answer:2},
        {text:"Tu ___ (recevoir) beaucoup de cadeaux pour ton anniversaire.", options:["reçois","recois","recevois"], answer:0},
        {text:"Elle ___ (revenir) de vacances la semaine prochaine.", options:["reviend","revient","revienne"], answer:1},
        {text:"Nous ___ (devoir) ranger nos affaires avant de partir.", options:["doivons","devions","devons"], answer:2},
        {text:"Il ___ (voir) très bien sans lunettes.", options:["voit","voie","vois"], answer:0},
        {text:"Il ___ (falloir) travailler régulièrement pour progresser.", options:["falloit","faut","faloit"], answer:1},
        {text:"Elle ___ (résoudre) tous les problèmes facilement.", options:["résoud","résoudt","résout"], answer:2},
        {text:"Tu ___ (rejoindre) tes amis après l'école.", options:["rejoins","rejoinds","rejoint"], answer:0},
        {text:"Il ___ (amener) son chien partout avec lui.", options:["amènet","amène","amenne"], answer:1},
        {text:"Elle ___ (craindre) les araignées.", options:["craind","craindt","craint"], answer:2},
        {text:"Je ___ (courir) tous les matins avant d'aller à l'école.", options:["cours","courre","coure"], answer:0},
        {text:"Tu ___ (venir) souvent nous rendre visite.", options:["vien","viens","vienne"], answer:1},
        {text:"Cette vieille plante ___ (mourir) faute d'eau.", options:["mourre","mourt","meurt"], answer:2},
        {text:"Grand-mère ___ (coudre) les vêtements abîmés.", options:["coud","cout","coudt"], answer:0},
        {text:"Il ___ (vivre) à la campagne depuis dix ans.", options:["vive","vit","vis"], answer:1},
        {text:"Tu ___ (conduire) prudemment en ville.", options:["conduits","conduies","conduis"], answer:2},
        {text:"Nous ___ (rire) beaucoup en regardant ce film.", options:["rirons","rions","rieons"], answer:1},
        {text:"Vous ___ (suivre) le guide pendant la visite.", options:["suivrez","suivez","suiviez"], answer:1},
        {text:"Il ___ (ouvrir) la fenêtre chaque matin.", options:["ouvret","ouvrt","ouvre"], answer:2},
        {text:"Nous ___ (offrir) un cadeau à notre maîtresse.", options:["ofrrons","offrons","offront"], answer:1},
        {text:"Je ___ (sortir) après avoir fini mes devoirs.", options:["sore","sors","sores"], answer:1},
      ],

      trous_bank: [
        {before:"En ce moment, nous", after:"une ligne droite sur notre feuille.", verb:"tracer", answer:"traçons"},
        {before:"Chaque midi, nous", after:"à la cantine avec nos amis.", verb:"manger", answer:"mangeons"},
        {before:"Ce matin, nous", after:"les chaises autour de la table.", verb:"placer", answer:"plaçons"},
        {before:"En été, nous", after:"dans la piscine municipale.", verb:"nager", answer:"nageons"},
        {before:"En ce moment, j'", after:"beaucoup de travail à la maison.", verb:"avoir", answer:"ai"},
        {before:"Tu", after:"très courageux dans cette situation difficile.", verb:"être", answer:"es"},
        {before:"Il", after:"toujours ses devoirs avant de regarder la télévision.", verb:"finir", answer:"finit"},
        {before:"Nous", after:"nos forces pour déplacer ce lourd meuble.", verb:"unir", answer:"unissons"},
        {before:"Vous", after:"déjà très bien conjuguer les verbes du premier groupe.", verb:"savoir", answer:"savez"},
        {before:"Elles", after:"venir nous aider si nous le leur demandons.", verb:"pouvoir", answer:"peuvent"},
        {before:"J'", after:"mes fruits et légumes au marché chaque samedi matin.", verb:"acheter", answer:"achète"},
        {before:"Tu", after:"tes vieux cahiers à la fin de chaque année scolaire.", verb:"jeter", answer:"jettes"},
        {before:"Il", after:"sa grand-mère tous les dimanches soirs.", verb:"appeler", answer:"appelle"},
        {before:"L'eau", after:"le long des rochers après la pluie.", verb:"ruisseler", answer:"ruissèle"},
        {before:"Elle", after:"ses enfants à l'école chaque matin à pied.", verb:"emmener", answer:"emmène"},
        {before:"Je", after:"la main pour répondre à la question du professeur.", verb:"lever", answer:"lève"},
        {before:"Ce long discours", after:"tout le monde dans la salle.", verb:"ennuyer", answer:"ennuie"},
        {before:"L'usine", after:"deux cents personnes dans notre région.", verb:"employer", answer:"emploie"},
        {before:"J'", after:"un message à mes parents pour les prévenir.", verb:"envoyer", answer:"envoie"},
        {before:"Tu", after:"la table après chaque repas sans qu'on te le demande.", verb:"essuyer", answer:"essuies"},
        {before:"Elle", after:"rapidement grâce aux médicaments du médecin.", verb:"guérir", answer:"guérit"},
        {before:"Je", after:"un roman passionnant en ce moment dans ma chambre.", verb:"lire", answer:"lis"},
        {before:"Nous", after:"une longue lettre à notre correspondant belge.", verb:"écrire", answer:"écrivons"},
        {before:"Tu", after:"ton manteau chaud avant de sortir dans le froid.", verb:"mettre", answer:"mets"},
        {before:"Il", after:"toujours la vérité à ses parents et à ses professeurs.", verb:"dire", answer:"dit"},
        {before:"Nous", after:"du sport ensemble chaque mercredi après-midi.", verb:"faire", answer:"faisons"},
        {before:"Les enfants", after:"du lait chaud chaque matin au petit-déjeuner.", verb:"boire", answer:"boivent"},
        {before:"L'artiste", after:"un magnifique tableau dans son atelier.", verb:"peindre", answer:"peint"},
        {before:"Tu ne", after:"jamais à tes amis ni à ta famille.", verb:"mentir", answer:"mens"},
        {before:"Elle", after:"la main de son petit frère pour traverser la rue.", verb:"tenir", answer:"tient"},
        {before:"Le directeur", after:"les nouveaux élèves avec beaucoup de gentillesse.", verb:"accueillir", answer:"accueille"},
        {before:"Je", after:"un grand verre d'eau fraîche, s'il te plaît.", verb:"vouloir", answer:"veux"},
        {before:"Nous", after:"au cinéma ensemble chaque vendredi soir.", verb:"aller", answer:"allons"},
        {before:"Tu", after:"beaucoup de cadeaux pour ton anniversaire chaque année.", verb:"recevoir", answer:"reçois"},
        {before:"Elle", after:"de ses vacances au Canada la semaine prochaine.", verb:"revenir", answer:"revient"},
        {before:"Nous", after:"ranger soigneusement nos affaires avant de partir.", verb:"devoir", answer:"devons"},
        {before:"Il", after:"très bien sans lunettes depuis son opération.", verb:"voir", answer:"voit"},
        {before:"Il", after:"travailler régulièrement pour progresser en classe.", verb:"falloir", answer:"faut"},
        {before:"Elle", after:"tous les problèmes de mathématiques très facilement.", verb:"résoudre", answer:"résout"},
        {before:"Tu", after:"tes amis au parc après l'école chaque jour.", verb:"rejoindre", answer:"rejoins"},
        {before:"Il", after:"son chien partout avec lui, même en vacances.", verb:"amener", answer:"amène"},
        {before:"Elle", after:"les araignées depuis qu'elle est toute petite.", verb:"craindre", answer:"craint"},
        {before:"Je", after:"tous les matins avant d'aller à l'école.", verb:"courir", answer:"cours"},
        {before:"Tu", after:"souvent nous rendre visite le week-end.", verb:"venir", answer:"viens"},
        {before:"Cette vieille plante", after:"faute d'eau et de lumière.", verb:"mourir", answer:"meurt"},
        {before:"Grand-mère", after:"les vêtements abîmés avec beaucoup de soin.", verb:"coudre", answer:"coud"},
        {before:"Il", after:"à la campagne depuis maintenant dix ans.", verb:"vivre", answer:"vit"},
        {before:"Tu", after:"prudemment en ville pour éviter les accidents.", verb:"conduire", answer:"conduis"},
        {before:"Il", after:"la fenêtre chaque matin pour aérer la chambre.", verb:"ouvrir", answer:"ouvre"},
        {before:"Je", after:"toujours après avoir fini tous mes devoirs.", verb:"sortir", answer:"sors"},
      ],

      evaluation: {
        qcm: [
          {text:"En ce moment, je ___ (aller) à l'école à pied.", options:["vais","vas","alle"], answer:0},
          {text:"Nous ___ (finir) notre travail avant midi.", options:["finisons","finirons","finissons"], answer:2},
          {text:"Je ___ (acheter) mes légumes au marché chaque samedi.", options:["achètte","achète","achette"], answer:1},
          {text:"Elle ___ (tenir) la main de son petit frère.", options:["tienne","tiend","tient"], answer:2},
          {text:"Tu ___ (recevoir) beaucoup de cadeaux pour ton anniversaire.", options:["reçois","recois","recevois"], answer:0},
        ],
        trous: [
          {before:"Chaque midi, nous", after:"à la cantine avec nos amis.", verb:"manger", answer:"mangeons"},
          {before:"Tu", after:"tes vieux cahiers à la fin de chaque année scolaire.", verb:"jeter", answer:"jettes"},
          {before:"Elle", after:"rapidement grâce aux médicaments du médecin.", verb:"guérir", answer:"guérit"},
          {before:"Il", after:"toujours la vérité à ses parents et à ses professeurs.", verb:"dire", answer:"dit"},
          {before:"Cette vieille plante", after:"faute d'eau et de lumière.", verb:"mourir", answer:"meurt"},
        ]
      }
    }

    // Ajouter ici les autres temps
    // ,present: { qcm_bank: [...], trous_bank: [...], evaluation: {...} }
    // ,imparfait: { qcm_bank: [...], trous_bank: [...], evaluation: {...} }
    // ,passe_compose: { qcm_bank: [...], trous_bank: [...], evaluation: {...} }
  }

  // Ajouter ici les autres sections
  // ,grammaire: { ... }
  // ,orthographe: { ... }
};
